countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Brazzaville)",
    "Congo (Kinshasa)",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor (Timor-Leste)",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]
governorates_egypt = [
    "Alexandria",
    "Aswan",
    "Assiut",
    "Beheira",
    "Beni Suef",
    "Cairo",
    "Dakahlia",
    "Damietta",
    "Faiyum",
    "Gharbia",
    "Giza",
    "Ismailia",
    "Kafr El Sheikh",
    "Luxor",
    "Matrouh",
    "Minya",
    "Monufia",
    "New Valley",
    "North Sinai",
    "Port Said",
    "Qalyubia",
    "Qena",
    "Red Sea",
    "Sharqia",
    "Sohag",
    "South Sinai",
    "Suez",
]
governorates_saudi_arabia = [
    "Riyadh",
    "Makkah",
    "Medina",
    "Eastern",
    "Al-Qassim",
    "Ha'il",
    "Tabuk",
    "Northern Borders",
    "Jizan",
    "Najran",
    "Al Bahah",
    "Al Jawf",
    "Asir",
]
governorates_palestine = [
    "Jenin",
    "Tubas",
    "Tulkarm",
    "Nablus",
    "Qalqilya",
    "Salfit",
    "Ramallah and Al-Bireh",
    "Jericho",
    "Jerusalem",
    "Bethlehem",
    "Hebron",
    "North Gaza",
    "Gaza",
    "Deir al-Balah",
    "Khan Yunis",
    "Rafah",
]
governorates_jordan = [
    "Ajloun",
    "Amman",
    "Aqaba",
    "Balqa",
    "Irbid",
    "Jerash",
    "Karak",
    "Ma'an",
    "Madaba",
    "Mafraq",
    "Tafilah",
    "Zarqa",
]
governorates_united_arab_emirates = [
    "Abu Dhabi",
    "Ajman",
    "Dubai",
    "Fujairah",
    "Ras Al Khaimah",
    "Sharjah",
    "Umm Al Quwain",
]
governorates_tunisia = [
    "Ariana",
    "Béja",
    "Ben Arous",
    "Bizerte",
    "Gabès",
    "Gafsa",
    "Jendouba",
    "Kairouan",
    "Kasserine",
    "Kebili",
    "Kef",
    "Mahdia",
    "Manouba",
    "Medenine",
    "Monastir",
    "Nabeul",
    "Sfax",
    "Sidi Bouzid",
    "Siliana",
    "Sousse",
    "Tataouine",
    "Tozeur",
    "Tunis",
    "Zaghouan",
]
governorates_algeria = [
    "Adrar",
    "Chlef",
    "Laghouat",
    "Oum El Bouaghi",
    "Batna",
    "Béjaïa",
    "Biskra",
    "Béchar",
    "Blida",
    "Bouira",
    "Tamanrasset",
    "Tébessa",
    "Tlemcen",
    "Tiaret",
    "Tizi Ouzou",
    "Algiers",
    "Djelfa",
    "Jijel",
    "Sétif",
    "Saïda",
    "Skikda",
    "Sidi Bel Abbès",
    "Annaba",
    "Guelma",
    "Constantine",
    "Médéa",
    "Mostaganem",
    "M'Sila",
    "Mascara",
    "Ouargla",
    "Oran",
    "El Bayadh",
    "Illizi",
    "Bordj Bou Arréridj",
    "Boumerdès",
    "El Tarf",
    "Tindouf",
    "Tissemsilt",
    "El Oued",
    "Khenchela",
    "Souk Ahras",
    "Tipaza",
    "Mila",
    "Aïn Defla",
    "Naâma",
    "Aïn Témouchent",
    "Ghardaïa",
    "Relizane",
    "El M'Ghair",
    "El Menia",
    "Ouled Djellal",
    "Bordj Baji Mokhtar",
    "Béni Abbès",
    "Timimoun",
    "Touggourt",
    "Djanet",
    "In Salah",
    "In Guezzam",
]
governorates_djibouti = [
    "Ali Sabieh Region",
    "Arta Region",
    "Dikhil Region",
    "Djibouti Region",
    "Obock Region",
    "Tadjourah Region",
]
governorates_sudan = [
    "Khartoum",
    "North Kurdufan",
    "Northern",
    "Kassala",
    "Blue Nile",
    "North Darfur",
    "South Darfur",
    "Gedaref",
    "Sennar",
    "White Nile",
    "River Nile",
    "Red Sea",
    "Al Jazirah",
    "West Darfur",
    "Central Darfur",
    "East Darfur",
    "West Kurdufan",
    "South Kurdufan",
]
governorates_syria = [
    "Al-Hasakah",
    "Aleppo",
    "Damascus",
    "Daraa",
    "Deir ez-Zor",
    "Hama",
    "Homs",
    "Idlib",
    "Latakia",
    "Quneitra",
    "Raqqa",
    "Rif Dimashq",
    "As-Suwayda",
    "Tartus",
]
governorates_somalia = [
    "Awdal",
    "Bakool",
    "Banaadir",
    "Bari",
    "Bay",
    "Galguduud",
    "Gedo",
    "Hiran",
    "Lower Juba",
    "Lower Shabelle",
    "Middle Juba",
    "Middle Shabelle",
    "Mudug",
    "Nugal",
    "Sanaag",
    "Sool",
    "Togdheer",
]
governorates_iraq = [
    "Al Anbar",
    "Babylon",
    "Baghdad",
    "Basra",
    "Dhi Qar",
    "Al-Qādisiyyah",
    "Diyala",
    "Duhok",
    "Erbil",
    "Karbala",
    "Kirkuk",
    "Maysan",
    "Muthanna",
    "Najaf",
    "Nineveh",
    "Saladin",
    "Sulaymaniyah",
    "Wasit",
]
governorates_oman = [
    "Ad Dakhiliyah",
    "Ad Dhahirah",
    "Al Batinah North",
    "Al Batinah South",
    "Al Buraimi",
    "Al Wusta",
    "Ash Sharqiyah North",
    "Ash Sharqiyah South",
    "Dhofar",
    "Musandam",
    "Muscat",
]
governorates_qatar = [
    "Al Daayen",
    "Al Khor and Al Thakhira",
    "Al Rayyan",
    "Al Shahaniya",
    "Doha",
    "Umm Salal",
    "Al Wakrah",
    "Al Shamal",
]
governorates_kuwait = [
    "Al Ahmadi",
    "Al Farwaniyah",
    "Al Asimah",
    "Jahra",
    "Hawalli",
    "Mubarak Al-Kabeer",
]
governorates_lebanon = [
    "Akkar",
    "Baalbek-Hermel",
    "Beirut",
    "Beqaa",
    "Mount Lebanon",
    "Nabatieh",
    "North Lebanon",
    "South Lebanon",
]
governorates_libya = [
    "Al Butnan",
    "Derna",
    "Al Jabal al Akhdar",
    "Al Marj",
    "Benghazi",
    "Al Wahat",
    "Kufra",
    "Sirte",
    "Misrata",
    "Al Murgub",
    "Tripoli",
    "Al Jfara",
    "Az Zawiyah",
    "An Nuqat al Khams",
    "Al Jabal al Gharbi",
    "Nalut",
    "Al Jufrah",
    "Wadi Al Shatii",
    "Sabha",
    "Wadi Al Hayaa",
    "Ghat",
    "Murzuq",
]
governorates_morocco = [
    "Tanger-Tetouan-Al Hoceima",
    "Oriental",
    "Fès-Meknès",
    "Rabat-Salé-Kénitra",
    "Béni Mellal-Khénifra",
    "Casablanca-Settat",
    "Marrakesh-Safi",
    "Drâa-Tafilalet",
    "Souss-Massa",
    "Guelmim-Oued Noun",
    "Laâyoune-Sakia El Hamra",
    "Dakhla-Oued Ed-Dahab",
]
governorates_mauritania = [
    "Adrar",
    "Assaba",
    "Brakna",
    "Dakhlet Nouadhibou",
    "Gorgol",
    "Guidimaka",
    "Hodh Ech Chargui",
    "Hodh El Gharbi",
    "Inchiri",
    "Nouakchott-Nord",
    "Nouakchott-Ouest",
    "Nouakchott-Sud",
    "Tagant",
    "Tiris Zemmour",
    "Trarza",
]
governorates_bahrain = [
    "Capital Governorate",
    "Muharraq Governorate",
    "Northern Governorate",
    "Southern Governorate",
]
governorates_comoros = [
    "Grande Comore",
    "Anjouan",
    "Mohéli",
]
governorates_afghanistan = [
    "Badakhshan",
    "Badghis",
    "Baghlan",
    "Balkh",
    "Bamyan",
    "Daykundi",
    "Farah",
    "Faryab",
    "Ghazni",
    "Ghor",
    "Helmand",
    "Herat",
    "Jowzjan",
    "Kabul",
    "Kandahar",
    "Kapisa",
    "Khost",
    "Kunar",
    "Kunduz",
    "Laghman",
    "Logar",
    "Nangarhar",
    "Nimruz",
    "Nuristan",
    "Paktika",
    "Paktiya",
    "Panjshir",
    "Parwan",
    "Samangan",
    "Sar-e Pol",
    "Takhar",
    "Urozgan",
    "Wardak",
    "Zabul",
]
governorates_albania = [
    "Berat",
    "Dibër",
    "Durrës",
    "Elbasan",
    "Fier",
    "Gjirokastër",
    "Korçë",
    "Kukës",
    "Lezhë",
    "Shkodër",
    "Tiranë",
    "Vlorë",
]
governorates_andorra = [
    "Andorra la Vella",
    "Canillo",
    "Encamp",
    "Escaldes-Engordany",
    "La Massana",
    "Ordino",
    "Sant Julià de Lòria",
]
governorates_angola = [
    "Bengo",
    "Benguela",
    "Bié",
    "Cabinda",
    "Cuando Cubango",
    "Cuanza Norte",
    "Cuanza Sul",
    "Cunene",
    "Huambo",
    "Huíla",
    "Luanda",
    "Lunda Norte",
    "Lunda Sul",
    "Malanje",
    "Moxico",
    "Namibe",
    "Uíge",
    "Zaire",
]
governorates_antigua_and_barbuda = [
    "Saint George Parish",
    "Saint John Parish",
    "Saint Mary Parish",
    "Saint Paul Parish",
    "Saint Peter Parish",
    "Saint Philip Parish",
    "Barbuda",
    "Redonda",
]
governorates_argentina = [
    "Buenos Aires",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Córdoba",
    "Corrientes",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego",
    "Tucumán",
]
governorates_armenia = [
    "Aragatsotn",
    "Ararat",
    "Armavir",
    "Gegharkunik",
    "Kotayk",
    "Lori",
    "Shirak",
    "Syunik",
    "Tavush",
    "Vayots Dzor",
    "Yerevan",
]
governorates_australia = [
    "New South Wales",
    "Victoria",
    "Queensland",
    "South Australia",
    "Western Australia",
    "Tasmania",
    "Australian Capital Territory",
    "Northern Territory",
]
governorates_austria = [
    "Burgenland",
    "Carinthia",
    "Lower Austria",
    "Upper Austria",
    "Salzburg",
    "Styria",
    "Tyrol",
    "Vorarlberg",
    "Vienna",
]
governorates_azerbaijan = [
    "Absheron",
    "Agdam",
    "Agdash",
    "Agjabadi",
    "Agstafa",
    "Agsu",
    "Astara",
    "Babek",
    "Baku",
    "Balakan",
    "Barda",
    "Beylagan",
    "Bilasuvar",
    "Dashkasan",
    "Fuzuli",
    "Ganja",
    "Gədəbəy",
    "Gobustan",
    "Goranboy",
    "Goychay",
    "Goygol",
    "Hajigabul",
    "Imishli",
    "Ismayilli",
    "Jabrayil",
    "Jalilabad",
    "Kalbajar",
    "Khachmaz",
    "Khojavend",
    "Khizi",
    "Khankendi",
    "Khojaly",
    "Kurdamir",
    "Lachin",
    "Lankaran",
    "Lankaran City",
    "Masally",
    "Mingachevir",
    "Nakhchivan Autonomous Republic",
    "Naftalan",
    "Neftchala",
    "Oghuz",
    "Qabala",
    "Qakh",
    "Qazakh",
    "Quba",
    "Qubadli",
    "Qusar",
    "Saatli",
    "Sabirabad",
    "Salyan",
    "Samukh",
    "Shirvan",
    "Shabran",
    "Shahbuz",
    "Shaki",
    "Shamkir",
    "Sharur",
    "Shirvan",
    "Shusha",
    "Siazan",
    "Sumgayit",
    "Tartar",
    "Tovuz",
    "Ujar",
    "Yardimli",
    "Yevlakh",
    "Zangilan",
    "Zaqatala",
    "Zardab",
]
governorates_bahamas = [
    "Acklins",
    "Berry Islands",
    "Bimini",
    "Black Point",
    "Cat Island",
    "Central Abaco",
    "Central Andros",
    "Central Eleuthera",
    "City of Freeport",
    "Crooked Island",
    "East Grand Bahama",
    "Exuma",
    "Grand Cay",
    "Harbour Island",
    "Hope Town",
    "Inagua",
    "Long Island",
    "Mangrove Cay",
    "Mayaguana",
    "Moores Island",
    "North Abaco",
    "North Andros",
    "North Eleuthera",
    "Ragged Island",
    "Rum Cay",
    "San Salvador",
    "South Abaco",
    "South Andros",
    "South Eleuthera",
    "Spanish Wells",
    "West Grand Bahama",
]
governorates_bangladesh = [
    "Barisal",
    "Chittagong",
    "Dhaka",
    "Khulna",
    "Mymensingh",
    "Rajshahi",
    "Rangpur",
    "Sylhet",
]
governorates_barbados = [
    "Christ Church",
    "Saint Andrew",
    "Saint George",
    "Saint James",
    "Saint John",
    "Saint Joseph",
    "Saint Lucy",
    "Saint Michael",
    "Saint Peter",
    "Saint Philip",
    "Saint Thomas",
]
governorates_belarus = [
    "Brest Region",
    "Gomel Region",
    "Grodno Region",
    "Minsk Region",
    "Mogilev Region",
    "Vitebsk Region",
    "Minsk (city)",
]
governorates_belgium = [
    "Antwerp",
    "East Flanders",
    "Flemish Brabant",
    "Limburg",
    "West Flanders",
    "Hainaut",
    "Liège",
    "Luxembourg",
    "Namur",
    "Walloon Brabant",
    "Brussels-Capital Region",
]
governorates_belize = [
    "Belize District",
    "Cayo District",
    "Corozal District",
    "Orange Walk District",
    "Stann Creek District",
    "Toledo District",
]
governorates_benin = [
    "Alibori",
    "Atacora",
    "Atlantique",
    "Borgou",
    "Collines",
    "Kouffo",
    "Donga",
    "Littoral",
    "Mono",
    "Ouémé",
    "Plateau",
    "Zou",
]
governorates_bhutan = [
    "Bumthang",
    "Chukha",
    "Dagana",
    "Gasa",
    "Haa",
    "Lhuntse",
    "Mongar",
    "Paro",
    "Pema Gatshel",
    "Punakha",
    "Samdrup Jongkhar",
    "Samtse",
    "Sarpang",
    "Thimphu",
    "Trashigang",
    "Trashiyangtse",
    "Trongsa",
    "Tsirang",
    "Wangdue Phodrang",
    "Zhemgang",
]
governorates_bolivia = [
    "Beni",
    "Chuquisaca",
    "Cochabamba",
    "La Paz",
    "Oruro",
    "Pando",
    "Potosí",
    "Santa Cruz",
    "Tarija",
]
governorates_bosnia_and_herzegovina = [
    "Federation of Bosnia and Herzegovina",
    "Republika Srpska",
    "Brčko District",
]
governorates_botswana = [
    "Central",
    "Ghanzi",
    "Kgalagadi",
    "Kgatleng",
    "Kweneng",
    "North-East",
    "North-West",
    "South-East",
    "Southern",
]
governorates_brazil = [
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Espírito Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Pará",
    "Paraíba",
    "Paraná",
    "Pernambuco",
    "Piauí",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Rondônia",
    "Roraima",
    "Santa Catarina",
    "São Paulo",
    "Sergipe",
    "Tocantins",
    "Federal District",
]
governorates_brunei = [
    "Belait",
    "Brunei-Muara",
    "Temburong",
    "Tutong",
]
governorates_bulgaria = [
    "Blagoevgrad",
    "Burgas",
    "Dobrich",
    "Gabrovo",
    "Haskovo",
    "Kardzhali",
    "Kyustendil",
    "Lovech",
    "Montana",
    "Pazardzhik",
    "Pernik",
    "Pleven",
    "Plovdiv",
    "Razgrad",
    "Ruse",
    "Shumen",
    "Silistra",
    "Sliven",
    "Smolyan",
    "Sofia City",
    "Sofia Province",
    "Stara Zagora",
    "Targovishte",
    "Varna",
    "Veliko Tarnovo",
    "Vidin",
    "Vratsa",
    "Yambol",
]
governorates_burkina_faso = [
    "Boucle du Mouhoun",
    "Cascades",
    "Centre",
    "Centre-Est",
    "Centre-Nord",
    "Centre-Ouest",
    "Centre-Sud",
    "Est",
    "Hauts-Bassins",
    "Nord",
    "Plateau-Central",
    "Sahel",
    "Sud-Ouest",
]
governorates_burundi = [
    "Bubanza",
    "Bujumbura Mairie",
    "Bujumbura Rural",
    "Bururi",
    "Cankuzo",
    "Cibitoke",
    "Gitega",
    "Karuzi",
    "Kayanza",
    "Kirundo",
    "Makamba",
    "Muramvya",
    "Muyinga",
    "Mwaro",
    "Ngozi",
    "Rumonge",
    "Rutana",
    "Ruyigi",
]
governorates_cabo_verde = [
    "Boa Vista",
    "Brava",
    "Maio",
    "Mosteiros",
    "Paul",
    "Porto Novo",
    "Praia",
    "Ribeira Brava",
    "Ribeira Grande",
    "Sal",
    "Santa Catarina",
    "Santa Cruz",
    "São Domingos",
    "São Filipe",
    "São Lourenço dos Órgãos",
    "São Miguel",
    "São Salvador do Mundo",
    "São Vicente",
    "Tarrafal",
]
governorates_cambodia = [
    "Banteay Meanchey",
    "Battambang",
    "Kampong Cham",
    "Kampong Chhnang",
    "Kampong Speu",
    "Kampong Thom",
    "Kampot",
    "Kandal",
    "Koh Kong",
    "Kratié",
    "Mondulkiri",
    "Oddar Meanchey",
    "Pailin",
    "Phnom Penh",
    "Preah Sihanouk",
    "Preah Vihear",
    "Pursat",
    "Ratanakiri",
    "Siem Reap",
    "Stung Treng",
    "Svay Rieng",
    "Takéo",
    "Tboung Khmum",
]
governorates_cameroon = [
    "Adamawa",
    "Centre",
    "East",
    "Far North",
    "Littoral",
    "North",
    "North-West",
    "South",
    "South-West",
    "West",
]
governorates_canada = [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Nova Scotia",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Northwest Territories",
    "Nunavut",
    "Yukon",
]
governorates_central_african_republic = [
    "Bamingui-Bangoran",
    "Bangui",
    "Basse-Kotto",
    "Haute-Kotto",
    "Haut-Mbomou",
    "Kémo",
    "Lobaye",
    "Mambéré-Kadéï",
    "Mbomou",
    "Nana-Grebizi",
    "Nana-Mambéré",
    "Ombella-M'Poko",
    "Ouaka",
    "Ouham",
    "Ouham-Pendé",
    "Sangha-Mbaéré",
    "Vakaga",
]
governorates_chad = [
    "Batha",
    "Chari-Baguirmi",
    "Hadjer-Lamis",
    "Kanem",
    "Lac",
    "Logone Occidental",
    "Logone Oriental",
    "Mandoul",
    "Mayo-Kebbi Est",
    "Mayo-Kebbi Ouest",
    "Moyen-Chari",
    "Ouaddaï",
    "Salamat",
    "Sila",
    "Tandjilé",
    "Tibesti",
    "Wadi Fira",
    "Borkou",
    "Ennedi-Est",
    "Ennedi-Ouest",
]
governorates_chile = [
    "Arica y Parinacota",
    "Tarapacá",
    "Antofagasta",
    "Atacama",
    "Coquimbo",
    "Valparaíso",
    "Santiago Metropolitan",
    "O'Higgins",
    "Maule",
    "Ñuble",
    "Biobío",
    "Araucanía",
    "Los Ríos",
    "Los Lagos",
    "Aysén",
    "Magallanes",
]
governorates_china = [
    "Anhui",
    "Fujian",
    "Gansu",
    "Guangdong",
    "Guizhou",
    "Hainan",
    "Hebei",
    "Heilongjiang",
    "Henan",
    "Hubei",
    "Hunan",
    "Jiangsu",
    "Jiangxi",
    "Jilin",
    "Liaoning",
    "Qinghai",
    "Shaanxi",
    "Shandong",
    "Shanxi",
    "Sichuan",
    "Yunnan",
    "Zhejiang",
    "Guangxi",
    "Inner Mongolia",
    "Ningxia",
    "Tibet",
    "Xinjiang",
    "Beijing",
    "Chongqing",
    "Shanghai",
    "Tianjin",
]
governorates_republic_of_the_congo = [
    "Bouenza",
    "Brazzaville",
    "Cuvette",
    "Cuvette-Ouest",
    "Kouilou",
    "Lékoumou",
    "Likouala",
    "Niari",
    "Plateaux",
    "Pointe-Noire",
    "Pool",
    "Sangha",
]
governorates_democratic_republic_of_the_congo = [
    "Bas-Uélé",
    "Équateur",
    "Haut-Katanga",
    "Haut-Lomami",
    "Haut-Uélé",
    "Ituri",
    "Kasaï",
    "Kasaï-Central",
    "Kasaï-Oriental",
    "Kinshasa",
    "Kongo Central",
    "Kwango",
    "Kwilu",
    "Lomami",
    "Lualaba",
    "Mai-Ndombe",
    "Maniema",
    "Mongala",
    "Nord-Kivu",
    "Nord-Ubangi",
    "Sankuru",
    "Sud-Kivu",
    "Sud-Ubangi",
    "Tanganyika",
    "Tshopo",
    "Tshuapa",
]
governorates_costa_rica = [
    "Alajuela",
    "Cartago",
    "Guanacaste",
    "Heredia",
    "Limón",
    "Puntarenas",
    "San José",
]
governorates_cote_d_ivoire = [
    "Abidjan",
    "Bas-Sassandra",
    "Comoé",
    "Denguélé",
    "Gôh-Djiboua",
    "Lacs",
    "Lagunes",
    "Montagnes",
    "Sassandra-Marahoué",
    "Savanes",
    "Vallée du Bandama",
    "Woroba",
    "Yamoussoukro",
    "Zanzan",
]
governorates_cuba = [
    "Artemisa",
    "Camagüey",
    "Ciego de Ávila",
    "Cienfuegos",
    "Granma",
    "Guantánamo",
    "Holguín",
    "Isla de la Juventud",
    "La Habana",
    "Las Tunas",
    "Matanzas",
    "Mayabeque",
    "Pinar del Río",
    "Sancti Spíritus",
    "Santiago de Cuba",
]
governorates_cyprus = [
    "Famagusta",
    "Kyrenia",
    "Larnaca",
    "Limassol",
    "Nicosia",
    "Paphos",
]
governorates_czech_republic = [
    "Prague",
    "Central Bohemian",
    "South Bohemian",
    "Plzeň",
    "Karlovy Vary",
    "Ústí nad Labem",
    "Liberec",
    "Hradec Králové",
    "Pardubice",
    "Olomouc",
    "Moravian-Silesian",
    "South Moravian",
    "Vysočina",
]
governorates_denmark = [
    "Capital Region of Denmark",
    "Central Denmark Region",
    "North Denmark Region",
    "Region Zealand",
    "Region of Southern Denmark",
]
governorates_dominica = [
    "Saint Andrew Parish",
    "Saint David Parish",
    "Saint George Parish",
    "Saint John Parish",
    "Saint Joseph Parish",
    "Saint Luke Parish",
    "Saint Mark Parish",
    "Saint Patrick Parish",
    "Saint Paul Parish",
    "Saint Peter Parish",
]
governorates_dominican_republic = [
    "Azua",
    "Baoruco",
    "Barahona",
    "Dajabón",
    "Distrito Nacional",
    "Duarte",
    "Elías Piña",
    "El Seibo",
    "Espaillat",
    "Hato Mayor",
    "Hermanas Mirabal",
    "Independencia",
    "La Altagracia",
    "La Romana",
    "La Vega",
    "María Trinidad Sánchez",
    "Monseñor Nouel",
    "Monte Cristi",
    "Monte Plata",
    "Pedernales",
    "Peravia",
    "Puerto Plata",
    "Samaná",
    "San Cristóbal",
    "San José de Ocoa",
    "San Juan",
    "San Pedro de Macorís",
    "Sánchez Ramírez",
    "Santiago",
    "Santiago Rodríguez",
    "Santo Domingo",
    "Valverde",
]
governorates_east_timor = [
    "Aileu",
    "Ainaro",
    "Baucau",
    "Bobonaro",
    "Cova Lima",
    "Dili",
    "Ermera",
    "Lautém",
    "Liquiçá",
    "Manatuto",
    "Manufahi",
    "Oecusse",
    "Viqueque",
]
governorates_ecuador = [
    "Azuay",
    "Bolívar",
    "Cañar",
    "Carchi",
    "Chimborazo",
    "Cotopaxi",
    "El Oro",
    "Esmeraldas",
    "Galápagos",
    "Guayas",
    "Imbabura",
    "Loja",
    "Los Ríos",
    "Manabí",
    "Morona-Santiago",
    "Napo",
    "Orellana",
    "Pastaza",
    "Pichincha",
    "Santa Elena",
    "Santo Domingo de los Tsáchilas",
    "Sucumbíos",
    "Tungurahua",
    "Zamora-Chinchipe",
]
governorates_el_salvador = [
    "Ahuachapán",
    "Cabañas",
    "Chalatenango",
    "Cuscatlán",
    "La Libertad",
    "La Paz",
    "La Unión",
    "Morazán",
    "San Miguel",
    "San Salvador",
    "San Vicente",
    "Santa Ana",
    "Sonsonate",
    "Usulután",
]
governorates_equatorial_guinea = [
    "Annobón",
    "Bioko Norte",
    "Bioko Sur",
    "Centro Sur",
    "Djibloho",
    "Kié-Ntem",
    "Litoral",
    "Wele-Nzas",
]
governorates_eritrea = [
    "Maekel Region",
    "Anseba Region",
    "Gash-Barka Region",
    "Southern Red Sea Region",
    "Northern Red Sea Region",
    "Debub Region",
]
governorates_estonia = [
    "Harju County",
    "Hiiu County",
    "Ida-Viru County",
    "Järva County",
    "Jõgeva County",
    "Lääne County",
    "Lääne-Viru County",
    "Pärnu County",
    "Põlva County",
    "Rapla County",
    "Saare County",
    "Tartu County",
    "Valga County",
    "Viljandi County",
    "Võru County",
]
governorates_eswatini = [
    "Hhohho",
    "Lubombo",
    "Manzini",
    "Shiselweni",
]
governorates_ethiopia = [
    "Addis Ababa",
    "Afar",
    "Amhara",
    "Benishangul-Gumuz",
    "Dire Dawa",
    "Gambela",
    "Harari",
    "Oromia",
    "Sidama",
    "Somali",
    "Southern Nations, Nationalities, and Peoples' Region",
    "South West Ethiopia Peoples' Region",
    "Tigray",
]
governorates_fiji = [
    "Central Division",
    "Eastern Division",
    "Northern Division",
    "Rotuma",
    "Western Division",
]
governorates_finland = [
    "Uusimaa",
    "Southwest Finland",
    "Satakunta",
    "Kanta-Häme",
    "Pirkanmaa",
    "Päijät-Häme",
    "Kymenlaakso",
    "South Karelia",
    "Southern Savonia",
    "Northern Savonia",
    "North Karelia",
    "Central Finland",
    "Southern Ostrobothnia",
    "Ostrobothnia",
    "Central Ostrobothnia",
    "Northern Ostrobothnia",
    "Kainuu",
    "Lapland",
    "Åland",
]
governorates_france = [
    "Auvergne-Rhône-Alpes",
    "Bourgogne-Franche-Comté",
    "Brittany",
    "Centre-Val de Loire",
    "Corsica",
    "Grand Est",
    "Hauts-de-France",
    "Île-de-France",
    "Normandy",
    "Nouvelle-Aquitaine",
    "Occitania",
    "Pays de la Loire",
    "Provence-Alpes-Côte d'Azur",
    "French Guiana",
    "Guadeloupe",
    "Martinique",
    "Mayotte",
    "Réunion",
]
governorates_gabon = [
    "Estuaire",
    "Haut-Ogooué",
    "Moyen-Ogooué",
    "Ngounié",
    "Nyanga",
    "Ogooué-Ivindo",
    "Ogooué-Lolo",
    "Ogooué-Maritime",
    "Woleu-Ntem",
]
governorates_gambia = [
    "Banjul",
    "Central River Division",
    "Lower River Division",
    "North Bank Division",
    "Upper River Division",
    "Western Division",
]
governorates_germany = [
    "Baden-Württemberg",
    "Bavaria",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hesse",
    "Lower Saxony",
    "Mecklenburg-Vorpommern",
    "North Rhine-Westphalia",
    "Rhineland-Palatinate",
    "Saarland",
    "Saxony",
    "Saxony-Anhalt",
    "Schleswig-Holstein",
    "Thuringia",
]
governorates_ghana = [
    "Ahafo Region",
    "Ashanti Region",
    "Bono East Region",
    "Bono Region",
    "Central Region",
    "Eastern Region",
    "Greater Accra Region",
    "North East Region",
    "Northern Region",
    "Oti Region",
    "Savannah Region",
    "Upper East Region",
    "Upper West Region",
    "Volta Region",
    "Western North Region",
    "Western Region",
]
governorates_greece = [
    "Attica",
    "Central Greece",
    "Central Macedonia",
    "Crete",
    "Eastern Macedonia and Thrace",
    "Epirus",
    "Ionian Islands",
    "North Aegean",
    "Peloponnese",
    "South Aegean",
    "Thessaly",
    "Western Greece",
    "Western Macedonia",
]
governorates_grenada = [
    "Saint Andrew Parish",
    "Saint David Parish",
    "Saint George Parish",
    "Saint John Parish",
    "Saint Mark Parish",
    "Saint Patrick Parish",
    "Carriacou and Petite Martinique",
]
governorates_guatemala = [
    "Alta Verapaz",
    "Baja Verapaz",
    "Chimaltenango",
    "Chiquimula",
    "El Progreso",
    "Escuintla",
    "Guatemala",
    "Huehuetenango",
    "Izabal",
    "Jalapa",
    "Jutiapa",
    "Petén",
    "Quetzaltenango",
    "Quiché",
    "Retalhuleu",
    "Sacatepéquez",
    "San Marcos",
    "Santa Rosa",
    "Sololá",
    "Suchitepéquez",
    "Totonicapán",
    "Zacapa",
]
governorates_guinea = [
    "Boké Region",
    "Conakry",
    "Faranah Region",
    "Kankan Region",
    "Kindia Region",
    "Labé Region",
    "Mamou Region",
    "Nzérékoré Region",
]
governorates_guinea_bissau = [
    "Bafatá",
    "Biombo",
    "Bissau",
    "Bolama",
    "Cacheu",
    "Gabú",
    "Oio",
    "Quinara",
    "Tombali",
]
governorates_guyana = [
    "Barima-Waini",
    "Cuyuni-Mazaruni",
    "Demerara-Mahaica",
    "East Berbice-Corentyne",
    "Essequibo Islands-West Demerara",
    "Mahaica-Berbice",
    "Pomeroon-Supenaam",
    "Potaro-Siparuni",
    "Upper Demerara-Berbice",
    "Upper Takutu-Upper Essequibo",
]
governorates_haiti = [
    "Artibonite",
    "Centre",
    "Grand'Anse",
    "Nippes",
    "Nord",
    "Nord-Est",
    "Nord-Ouest",
    "Ouest",
    "Sud",
    "Sud-Est",
]
governorates_honduras = [
    "Atlántida",
    "Choluteca",
    "Colón",
    "Comayagua",
    "Copán",
    "Cortés",
    "El Paraíso",
    "Francisco Morazán",
    "Gracias a Dios",
    "Intibucá",
    "Islas de la Bahía",
    "La Paz",
    "Lempira",
    "Ocotepeque",
    "Olancho",
    "Santa Bárbara",
    "Valle",
    "Yoro",
]
governorates_hungary = [
    "Bács-Kiskun",
    "Baranya",
    "Békés",
    "Borsod-Abaúj-Zemplén",
    "Budapest",
    "Csongrád-Csanád",
    "Fejér",
    "Győr-Moson-Sopron",
    "Hajdú-Bihar",
    "Heves",
    "Jász-Nagykun-Szolnok",
    "Komárom-Esztergom",
    "Nógrád",
    "Pest",
    "Somogy",
    "Szabolcs-Szatmár-Bereg",
    "Tolna",
    "Vas",
    "Veszprém",
    "Zala",
]
governorates_iceland = [
    "Capital Region",
    "Southern Peninsula",
    "Western Region",
    "Westfjords",
    "Northwestern Region",
    "Northeastern Region",
    "Eastern Region",
    "Southern Region",
]
governorates_india = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry",
]
governorates_indonesia = [
    "Aceh",
    "Bali",
    "Bangka Belitung Islands",
    "Banten",
    "Bengkulu",
    "Central Java",
    "Central Kalimantan",
    "Central Sulawesi",
    "East Java",
    "East Kalimantan",
    "East Nusa Tenggara",
    "Gorontalo",
    "Jakarta",
    "Jambi",
    "Lampung",
    "Maluku",
    "North Kalimantan",
    "North Maluku",
    "North Sulawesi",
    "North Sumatra",
    "Papua",
    "Riau",
    "Riau Islands",
    "South Kalimantan",
    "South Sulawesi",
    "South Sumatra",
    "Southeast Sulawesi",
    "West Java",
    "West Kalimantan",
    "West Nusa Tenggara",
    "West Papua",
    "West Sulawesi",
    "West Sumatra",
    "Special Region of Yogyakarta",
]
governorates_iran = [
    "Alborz",
    "Ardabil",
    "Bushehr",
    "Chaharmahal and Bakhtiari",
    "East Azerbaijan",
    "Isfahan",
    "Fars",
    "Gilan",
    "Golestan",
    "Hamadan",
    "Hormozgan",
    "Ilam",
    "Kerman",
    "Kermanshah",
    "Khuzestan",
    "Kohgiluyeh and Boyer-Ahmad",
    "Kurdistan",
    "Lorestan",
    "Markazi",
    "Mazandaran",
    "North Khorasan",
    "Qazvin",
    "Qom",
    "Razavi Khorasan",
    "Semnan",
    "Sistan and Baluchestan",
    "South Khorasan",
    "Tehran",
    "West Azerbaijan",
    "Yazd",
    "Zanjan",
]
governorates_ireland = [
    # Provinces
    "Connacht",
    "Leinster",
    "Munster",
    "Ulster",
    # Counties
    "Carlow",
    "Cavan",
    "Clare",
    "Cork",
    "Donegal",
    "Dublin",
    "Galway",
    "Kerry",
    "Kildare",
    "Kilkenny",
    "Laois",
    "Leitrim",
    "Limerick",
    "Longford",
    "Louth",
    "Mayo",
    "Meath",
    "Monaghan",
    "Offaly",
    "Roscommon",
    "Sligo",
    "Tipperary",
    "Waterford",
    "Westmeath",
    "Wexford",
    "Wicklow",
]
governorates_italy = [
    "Abruzzo",
    "Aosta Valley",
    "Apulia",
    "Basilicata",
    "Calabria",
    "Campania",
    "Emilia-Romagna",
    "Friuli-Venezia Giulia",
    "Lazio",
    "Liguria",
    "Lombardy",
    "Marche",
    "Molise",
    "Piedmont",
    "Sardinia",
    "Sicily",
    "Trentino-Alto Adige",
    "Tuscany",
    "Umbria",
    "Veneto",
]
governorates_jamaica = [
    "Clarendon",
    "Hanover",
    "Kingston",
    "Manchester",
    "Portland",
    "Saint Andrew",
    "Saint Ann",
    "Saint Catherine",
    "Saint Elizabeth",
    "Saint James",
    "Saint Mary",
    "Saint Thomas",
    "Trelawny",
    "Westmoreland",
]
governorates_japan = [
    "Aichi",
    "Akita",
    "Aomori",
    "Chiba",
    "Ehime",
    "Fukui",
    "Fukuoka",
    "Fukushima",
    "Gifu",
    "Gunma",
    "Hiroshima",
    "Hokkaido",
    "Hyogo",
    "Ibaraki",
    "Ishikawa",
    "Iwate",
    "Kagawa",
    "Kagoshima",
    "Kanagawa",
    "Kochi",
    "Kumamoto",
    "Kyoto",
    "Mie",
    "Miyagi",
    "Miyazaki",
    "Nagano",
    "Nagasaki",
    "Nara",
    "Niigata",
    "Oita",
    "Okayama",
    "Okinawa",
    "Osaka",
    "Saga",
    "Saitama",
    "Shiga",
    "Shimane",
    "Shizuoka",
    "Tochigi",
    "Tokushima",
    "Tokyo",
    "Tottori",
    "Toyama",
    "Wakayama",
    "Yamagata",
    "Yamaguchi",
    "Yamanashi",
]
governorates_kazakhstan = [
    "Akmola Region",
    "Aktobe Region",
    "Almaty Region",
    "Atyrau Region",
    "East Kazakhstan Region",
    "Jambyl Region",
    "Karaganda Region",
    "Kostanay Region",
    "Kyzylorda Region",
    "Mangystau Region",
    "North Kazakhstan Region",
    "Pavlodar Region",
    "Turkistan Region",
    "West Kazakhstan Region",
    "Almaty (city)",
    "Nur-Sultan (city)",
    "Shymkent (city)",
]
governorates_kenya = [
    "Baringo",
    "Bomet",
    "Bungoma",
    "Busia",
    "Elgeyo-Marakwet",
    "Embu",
    "Garissa",
    "Homa Bay",
    "Isiolo",
    "Kajiado",
    "Kakamega",
    "Kericho",
    "Kiambu",
    "Kilifi",
    "Kirinyaga",
    "Kisii",
    "Kisumu",
    "Kitui",
    "Kwale",
    "Laikipia",
    "Lamu",
    "Machakos",
    "Makueni",
    "Mandera",
    "Marsabit",
    "Meru",
    "Migori",
    "Mombasa",
    "Murang'a",
    "Nairobi",
    "Nakuru",
    "Nandi",
    "Narok",
    "Nyamira",
    "Nyandarua",
    "Nyeri",
    "Samburu",
    "Siaya",
    "Taita-Taveta",
    "Tana River",
    "Tharaka-Nithi",
    "Trans-Nzoia",
    "Turkana",
    "Uasin Gishu",
    "Vihiga",
    "Wajir",
    "West Pokot",
]
governorates_kiribati = [
    "Gilbert Islands",
    "Line Islands",
    "Phoenix Islands",
]
governorates_kosovo = [
    "District of Gjakova",
    "District of Gjilan",
    "District of Mitrovica",
    "District of Peja",
    "District of Pristina",
    "District of Prizren",
    "District of Ferizaj",
]
governorates_kyrgyzstan = [
    "Batken Region",
    "Chuy Region",
    "Jalal-Abad Region",
    "Naryn Region",
    "Osh Region",
    "Talas Region",
    "Issyk-Kul Region",
    "Bishkek (city)",
    "Osh (city)",
]
governorates_laos = [
    "Attapeu Province",
    "Bokeo Province",
    "Bolikhamsai Province",
    "Champasak Province",
    "Houaphanh Province",
    "Khammouane Province",
    "Luang Namtha Province",
    "Luang Prabang Province",
    "Oudomxay Province",
    "Phongsaly Province",
    "Salavan Province",
    "Savannakhet Province",
    "Vientiane Province",
    "Sekong Province",
    "Vientiane Prefecture",
    "Xaisomboun Province",
    "Xaisomboun Special Zone (former)",
    "Xiangkhouang Province",
]
governorates_latvia = [
    "Aizkraukle Municipality",
    "Alūksne Municipality",
    "Balvi Municipality",
    "Bauska Municipality",
    "Cēsis Municipality",
    "Daugavpils Municipality",
    "Dobele Municipality",
    "Gulbene Municipality",
    "Jelgava Municipality",
    "Jēkabpils Municipality",
    "Ķekava Municipality",
    "Krāslava Municipality",
    "Kuldīga Municipality",
    "Limbaži Municipality",
    "Līvāni Municipality",
    "Ludza Municipality",
    "Madona Municipality",
    "Ogre Municipality",
    "Olaine Municipality",
    "Preiļi Municipality",
    "Rēzekne Municipality",
    "Ropaži Municipality",
    "Salaspils Municipality",
    "Saldus Municipality",
    "Saulkrasti Municipality",
    "Sigulda Municipality",
    "Smiltene Municipality",
    "South Kurzeme Municipality",
    "Talsi Municipality",
    "Tukums Municipality",
    "Valka Municipality",
    "Valmiera Municipality",
    "Varakļāni Municipality",
    "Ventspils Municipality",
    "Jūrmala (city)",
    "Liepāja (city)",
    "Rīga (city)",
    "Ventspils (city)",
]
governorates_lesotho = [
    "Berea District",
    "Butha-Buthe District",
    "Leribe District",
    "Mafeteng District",
    "Maseru District",
    "Mohale's Hoek District",
    "Mokhotlong District",
    "Qacha's Nek District",
    "Quthing District",
    "Thaba-Tseka District",
]
governorates_liberia = [
    "Bomi County",
    "Bong County",
    "Gbarpolu County",
    "Grand Bassa County",
    "Grand Cape Mount County",
    "Grand Gedeh County",
    "Grand Kru County",
    "Lofa County",
    "Margibi County",
    "Maryland County",
    "Montserrado County",
    "Nimba County",
    "River Cess County",
    "River Gee County",
    "Sinoe County",
]
governorates_liechtenstein = [
    "Balzers",
    "Eschen",
    "Gamprin",
    "Mauren",
    "Planken",
    "Ruggell",
    "Schaan",
    "Schellenberg",
    "Triesen",
    "Triesenberg",
    "Vaduz",
]
governorates_lithuania = [
    "Alytus County",
    "Kaunas County",
    "Klaipėda County",
    "Marijampolė County",
    "Panevėžys County",
    "Šiauliai County",
    "Tauragė County",
    "Telšiai County",
    "Utena County",
    "Vilnius County",
]
governorates_luxembourg = [
    "Diekirch District",
    "Grevenmacher District",
    "Luxembourg District",
]
governorates_madagascar = [
    "Analamanga",
    "Amoron'i Mania",
    "Atsimo-Andrefana",
    "Atsimo-Atsinanana",
    "Atsinanana",
    "Boeny",
    "Bongolava",
    "Diana",
    "Haute Matsiatra",
    "Ihorombe",
    "Itasy",
    "Alaotra-Mangoro",
    "Melaky",
    "Menabe",
    "Sava",
    "Sofia",
    "Vakinankaratra",
    "Vatovavy-Fitovinany",
]
governorates_malawi = [
    "Balaka",
    "Blantyre",
    "Chikwawa",
    "Chiradzulu",
    "Chitipa",
    "Dedza",
    "Dowa",
    "Karonga",
    "Kasungu",
    "Likoma",
    "Lilongwe",
    "Machinga",
    "Mangochi",
    "Mchinji",
    "Mulanje",
    "Mwanza",
    "Mzimba",
    "Neno",
    "Nkhata Bay",
    "Nkhotakota",
    "Nsanje",
    "Ntcheu",
    "Ntchisi",
    "Phalombe",
    "Rumphi",
    "Salima",
    "Thyolo",
    "Zomba",
]
governorates_malaysia = [
    "Johor",
    "Kedah",
    "Kelantan",
    "Malacca",
    "Negeri Sembilan",
    "Pahang",
    "Penang",
    "Perak",
    "Perlis",
    "Sabah",
    "Sarawak",
    "Selangor",
    "Terengganu",
    "Kuala Lumpur",
    "Labuan",
    "Putrajaya",
]
governorates_maldives = [
    "Addu City",
    "Fuvahmulah",
    "Malé City",
    "Haa Alifu Atoll",
    "Haa Dhaalu Atoll",
    "Shaviyani Atoll",
    "Noonu Atoll",
    "Raa Atoll",
    "Baa Atoll",
    "Lhaviyani Atoll",
    "Kaafu Atoll",
    "Alifu Alifu Atoll",
    "Alifu Dhaalu Atoll",
    "Vaavu Atoll",
    "Meemu Atoll",
    "Faafu Atoll",
    "Dhaalu Atoll",
    "Thaa Atoll",
    "Laamu Atoll",
    "Gaafu Alifu Atoll",
    "Gaafu Dhaalu Atoll",
    "Gnaviyani Atoll",
]
governorates_mali = [
    "Bamako",
    "Gao",
    "Kayes",
    "Kidal",
    "Koulikoro",
    "Mopti",
    "Ségou",
    "Sikasso",
    "Tombouctou",
]
governorates_malta = [
    "Gozo and Comino",
    "Northern Region",
    "Southeastern Region",
    "Southern Region",
    "Central Region",
]
governorates_marshall_islands = [
    "Ailinglaplap",
    "Ailuk",
    "Arno",
    "Aur",
    "Ebon",
    "Enen-Kio",
    "Jabat",
    "Jaluit",
    "Kili",
    "Kwajalein",
    "Lae",
    "Lib",
    "Likiep",
    "Majuro",
    "Maloelap",
    "Mejit",
    "Mili",
    "Namorik",
    "Namu",
    "Rongelap",
    "Ujae",
    "Utrik",
    "Wotho",
    "Wotje",
]
governorates_mauritius = [
    "Black River",
    "Flacq",
    "Grand Port",
    "Moka",
    "Pamplemousses",
    "Plaines Wilhems",
    "Port Louis",
    "Rivière du Rempart",
    "Savanne",
    "Agalega Islands",
    "Cargados Carajos Shoals (Saint Brandon)",
    "Rodrigues Island",
]
governorates_mexico = [
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Coahuila",
    "Colima",
    "Durango",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "México",
    "Michoacán",
    "Morelos",
    "Nayarit",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Querétaro",
    "Quintana Roo",
    "San Luis Potosí",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatán",
    "Zacatecas",
]
governorates_micronesia = [
    "Chuuk",
    "Kosrae",
    "Pohnpei",
    "Yap",
]
governorates_moldova = [
    "Anenii Noi District",
    "Basarabeasca District",
    "Briceni District",
    "Cahul District",
    "Cantemir District",
    "Călărași District",
    "Căușeni District",
    "Cimișlia District",
    "Criuleni District",
    "Dondușeni District",
    "Drochia District",
    "Dubăsari District",
    "Edineț District",
    "Fălești District",
    "Florești District",
    "Glodeni District",
    "Hîncești District",
    "Ialoveni District",
    "Leova District",
    "Nisporeni District",
    "Ocnița District",
    "Orhei District",
    "Rezina District",
    "Rîșcani District",
    "Sîngerei District",
    "Șoldănești District",
    "Soroca District",
    "Ștefan Vodă District",
    "Strășeni District",
    "Taraclia District",
    "Telenești District",
    "Ungheni District",
    "Chisinau (municipality)",
    "Bălți (municipality)",
    "Bender (municipality)",
    "Comrat (municipality)",
    "Tiraspol (municipality)",
    "Gagauzia (autonomous territorial unit)",
]
governorates_monaco = [
    # Monaco is a city-state and has no administrative divisions
    "monaco_city"
]
governorates_mongolia = [
    "Arkhangai",
    "Bayankhongor",
    "Bayan-Ölgii",
    "Bulgan",
    "Darkhan-Uul",
    "Dornod",
    "Dornogovi",
    "Dundgovi",
    "Govi-Altai",
    "Govisümber",
    "Khentii",
    "Khovd",
    "Khövsgöl",
    "Ömnögovi",
    "Orkhon",
    "Övörkhangai",
    "Selenge",
    "Sükhbaatar",
    "Töv",
    "Ulaanbaatar",
    "Uvs",
    "Zavkhan",
]
governorates_mozambique = [
    "Cabo Delgado",
    "Gaza",
    "Inhambane",
    "Manica",
    "Maputo Province",
    "Nampula",
    "Niassa",
    "Sofala",
    "Tete",
    "Zambezia",
]
governorates_myanmar = [
    "Ayeyarwady Region",
    "Bago Region",
    "Magway Region",
    "Mandalay Region",
    "Sagaing Region",
    "Tanintharyi Region",
    "Yangon Region",
    "Chin State",
    "Kachin State",
    "Kayah State",
    "Kayin State",
    "Mon State",
    "Rakhine State",
    "Shan State",
]
governorates_namibia = [
    "Kunene Region",
    "Omusati Region",
    "Oshana Region",
    "Ohangwena Region",
    "Oshikoto Region",
    "Kavango East Region",
    "Kavango West Region",
    "Zambezi Region",
    "Otjozondjupa Region",
    "Erongo Region",
    "Khomas Region",
    "Hardap Region",
    "Karas Region",
    "Omaheke Region",
]
governorates_nauru = [
    "Aiwo District",
    "Anabar District",
    "Anetan District",
    "Anibare District",
    "Baiti District",
    "Boe District",
    "Buada District",
    "Denigomodu District",
    "Ewa District",
    "Ijuw District",
    "Meneng District",
    "Nibok District",
    "Uaboe District",
    "Yaren District",
]
governorates_netherlands = [
    "Drenthe",
    "Flevoland",
    "Friesland",
    "Gelderland",
    "Groningen",
    "Limburg",
    "North Brabant",
    "North Holland",
    "Overijssel",
    "South Holland",
    "Utrecht",
    "Zeeland",
]
governorates_nicaragua = [
    "Boaco Department",
    "Carazo Department",
    "Chinandega Department",
    "Chontales Department",
    "Estelí Department",
    "Granada Department",
    "Jinotega Department",
    "León Department",
    "Madriz Department",
    "Managua Department",
    "Masaya Department",
    "Matagalpa Department",
    "Nueva Segovia Department",
    "Rivas Department",
    "Río San Juan Department",
    "North Caribbean Coast Autonomous Region",
    "South Caribbean Coast Autonomous Region",
]
governorates_niger = [
    "Agadez Region",
    "Diffa Region",
    "Dosso Region",
    "Maradi Region",
    "Tahoua Region",
    "Tillabéri Region",
    "Zinder Region",
]
governorates_nigeria = [
    "Abia State",
    "Adamawa State",
    "Akwa Ibom State",
    "Anambra State",
    "Bauchi State",
    "Bayelsa State",
    "Benue State",
    "Borno State",
    "Cross River State",
    "Delta State",
    "Ebonyi State",
    "Edo State",
    "Ekiti State",
    "Enugu State",
    "Gombe State",
    "Imo State",
    "Jigawa State",
    "Kaduna State",
    "Kano State",
    "Katsina State",
    "Kebbi State",
    "Kogi State",
    "Kwara State",
    "Lagos State",
    "Nasarawa State",
    "Niger State",
    "Ogun State",
    "Ondo State",
    "Osun State",
    "Oyo State",
    "Plateau State",
    "Rivers State",
    "Sokoto State",
    "Taraba State",
    "Yobe State",
    "Zamfara State",
    "Federal Capital Territory",
]
governorates_north_korea = [
    "Chagang Province",
    "North Hamgyong Province",
    "South Hamgyong Province",
    "North Hwanghae Province",
    "South Hwanghae Province",
    "Kangwon Province",
    "North Pyongan Province",
    "South Pyongan Province",
    "Ryanggang Province",
    "Pyongyang (city)",
    "Rason (city)",
]
governorates_north_macedonia = [
    "Aerodrom",
    "Aračinovo",
    "Berovo",
    "Bitola",
    "Bogdanci",
    "Bogovinje",
    "Bosilovo",
    "Brvenica",
    "Butel",
    "Čair",
    "Čaška",
    "Centar",
    "Centar Župa",
    "Češinovo-Obleševo",
    "Čučer-Sandevo",
    "Debarca",
    "Delčevo",
    "Demir Hisar",
    "Demir Kapija",
    "Dolneni",
    "Drugovo",
    "Gazi Baba",
    "Gevgelija",
    "Gjorče Petrov",
    "Gostivar",
    "Gradsko",
    "Ilinden",
    "Jegunovce",
    "Karbinci",
    "Karpoš",
    "Kavadarci",
    "Kičevo",
    "Kisela Voda",
    "Kočani",
    "Konče",
    "Kratovo",
    "Kriva Palanka",
    "Krivogaštani",
    "Kruševo",
    "Kumanovo",
    "Lipkovo",
    "Lozovo",
    "Makedonska Kamenica",
    "Makedonski Brod",
    "Mavrovo and Rostuša",
    "Mogila",
    "Negotino",
    "Novaci",
    "Novo Selo",
    "Ohrid",
    "Pehčevo",
    "Petrovec",
    "Plasnica",
    "Prilep",
    "Probištip",
    "Radoviš",
    "Rankovce",
    "Resen",
    "Rosoman",
    "Saraj",
    "Sopište",
    "Staro Nagoričane",
    "Štip",
    "Struga",
    "Strumica",
    "Studeničani",
    "Šuto Orizari",
    "Tearce",
    "Tetovo",
    "Valandovo",
    "Vasilevo",
    "Veles",
    "Vevčani",
    "Vinica",
    "Vrapčište",
    "Zelenikovo",
    "Zrnovci",
]
governorates_norway = [
    "Agder",
    "Innlandet",
    "Møre og Romsdal",
    "Nordland",
    "Oslo",
    "Rogaland",
    "Vestfold og Telemark",
    "Troms og Finnmark",
    "Trøndelag",
    "Vestland",
]
governorates_pakistan = [
    "Azad Jammu and Kashmir",
    "Balochistan",
    "Gilgit-Baltistan",
    "Islamabad Capital Territory",
    "Khyber Pakhtunkhwa",
    "Punjab",
    "Sindh",
]
governorates_palau = [
    "Aimeliik",
    "Airai",
    "Angaur",
    "Hatohobei",
    "Kayangel",
    "Koror",
    "Melekeok",
    "Ngaraard",
    "Ngarchelong",
    "Ngardmau",
    "Ngatpang",
    "Ngchesar",
    "Ngeremlengui",
    "Ngiwal",
    "Peleliu",
    "Sonsorol",
]
governorates_panama = [
    "Bocas del Toro Province",
    "Chiriquí Province",
    "Coclé Province",
    "Colón Province",
    "Darién Province",
    "Herrera Province",
    "Los Santos Province",
    "Panamá Oeste Province",
    "Panamá Province",
    "Veraguas Province",
    "Emberá-Wounaan Comarca",
    "Guna Yala Comarca",
    "Ngöbe-Buglé Comarca",
]
governorates_papua_new_guinea = [
    "Central Province",
    "Chimbu Province",
    "East New Britain Province",
    "East Sepik Province",
    "Enga Province",
    "Gulf Province",
    "Hela Province",
    "Jiwaka Province",
    "Madang Province",
    "Manus Province",
    "Milne Bay Province",
    "Morobe Province",
    "New Ireland Province",
    "Northern Province (Oro)",
    "Bougainville (Autonomous Region)",
    "Southern Highlands Province",
    "West New Britain Province",
    "West Sepik Province (Sandaun)",
    "Western Province",
    "Western Highlands Province",
]
governorates_paraguay = [
    "Alto Paraguay Department",
    "Alto Paraná Department",
    "Amambay Department",
    "Boquerón Department",
    "Caaguazú Department",
    "Caazapá Department",
    "Canindeyú Department",
    "Central Department",
    "Concepción Department",
    "Cordillera Department",
    "Guairá Department",
    "Itapúa Department",
    "Misiones Department",
    "Ñeembucú Department",
    "Paraguarí Department",
    "Presidente Hayes Department",
    "San Pedro Department",
    "Asunción (Capital District)",
]
governorates_poland = [
    "Greater Poland Voivodeship",
    "Kuyavian-Pomeranian Voivodeship",
    "Lesser Poland Voivodeship",
    "Łódź Voivodeship",
    "Lower Silesian Voivodeship",
    "Lublin Voivodeship",
    "Lubusz Voivodeship",
    "Masovian Voivodeship",
    "Opole Voivodeship",
    "Podkarpackie Voivodeship",
    "Podlaskie Voivodeship",
    "Pomeranian Voivodeship",
    "Silesian Voivodeship",
    "Świętokrzyskie Voivodeship",
    "Warmian-Masurian Voivodeship",
    "West Pomeranian Voivodeship",
]
governorates_portugal = [
    "Alentejo",
    "Algarve",
    "Centro",
    "Lisbon Metropolitan Area",
    "Norte",
    "Azores Autonomous Region",
    "Madeira Autonomous Region",
]
governorates_romania = [
    "Alba County",
    "Arad County",
    "Argeș County",
    "Bacău County",
    "Bihor County",
    "Bistrița-Năsăud County",
    "Botoșani County",
    "Brașov County",
    "Brăila County",
    "Buzău County",
    "Caraș-Severin County",
    "Călărași County",
    "Cluj County",
    "Constanța County",
    "Covasna County",
    "Dâmbovița County",
    "Dolj County",
    "Galați County",
    "Giurgiu County",
    "Gorj County",
    "Harghita County",
    "Hunedoara County",
    "Ialomița County",
    "Iași County",
    "Ilfov County",
    "Maramureș County",
    "Mehedinți County",
    "Mureș County",
    "Neamț County",
    "Olt County",
    "Prahova County",
    "Satu Mare County",
    "Sălaj County",
    "Sibiu County",
    "Suceava County",
    "Teleorman County",
    "Timiș County",
    "Tulcea County",
    "Vaslui County",
    "Vâlcea County",
    "Vrancea County",
    "Bucharest (municipality)",
]
governorates_russia = [
    "Altai Krai",
    "Amur Oblast",
    "Arkhangelsk Oblast",
    "Astrakhan Oblast",
    "Bashkortostan Republic",
    "Belgorod Oblast",
    "Chechen Republic",
    "Chuvash Republic",
    "Dagestan Republic",
    "Irkutsk Oblast",
    "Kaliningrad Oblast",
    "Kemerovo Oblast",
    "Krasnodar Krai",
    "Krasnoyarsk Krai",
    "Leningrad Oblast",
    "Moscow (federal city)",
    "Nizhny Novgorod Oblast",
    "Novosibirsk Oblast",
    "Omsk Oblast",
    "Perm Krai",
    "Rostov Oblast",
    "Saint Petersburg (federal city)",
    "Sakha Republic",
    "Samara Oblast",
    "Sverdlovsk Oblast",
    "Tatarstan Republic",
    "Tula Oblast",
    "Tyumen Oblast",
    "Udmurt Republic",
    "Volgograd Oblast",
    "Voronezh Oblast",
]
governorates_rwanda = [
    "Eastern Province",
    "Northern Province",
    "Southern Province",
    "Western Province",
    "Kigali City",
]
governorates_saint_lucia = [
    "Anse la Raye Quarter",
    "Canaries Quarter",
    "Castries Quarter",
    "Choiseul Quarter",
    "Dennery Quarter",
    "Gros Islet Quarter",
    "Laborie Quarter",
    "Micoud Quarter",
    "Soufrière Quarter",
    "Vieux Fort Quarter",
]
governorates_saint_vincent_and_the_grenadines = [
    "Charlotte Parish",
    "Saint George Parish",
    "Saint Andrew Parish",
    "Saint Patrick Parish",
    "Saint David Parish",
    "Grenadines Parish",
]
governorates_samoa = [
    "A'ana",
    "Aiga-i-le-Tai",
    "Atua",
    "Fa'asaleleaga",
    "Gaga'emauga",
    "Gaga'ifomauga",
    "Palauli",
    "Satupa'itea",
    "Tuamasaga",
    "Va'a-o-Fonoti",
    "Vaisigano",
]
governorates_san_marino = [
    "Acquaviva",
    "Borgo Maggiore",
    "Chiesanuova",
    "Domagnano",
    "Faetano",
    "Fiorentino",
    "Montegiardino",
    "San Marino",
    "Serravalle",
]
governorates_sao_tome_and_principe = [
    "Água Grande District",
    "Cantagalo District",
    "Caué District",
    "Lembá District",
    "Lobata District",
    "Mé-Zóchi District",
    "Pagué District",
]
governorates_senegal = [
    "Dakar Region",
    "Diourbel Region",
    "Fatick Region",
    "Kaffrine Region",
    "Kaolack Region",
    "Kédougou Region",
    "Kolda Region",
    "Louga Region",
    "Matam Region",
    "Saint-Louis Region",
    "Sédhiou Region",
    "Tambacounda Region",
    "Thiès Region",
    "Ziguinchor Region",
]
governorates_serbia = [
    "Belgrade City",
    "Bor District",
    "Braničevo District",
    "Jablanica District",
    "Kolubara District",
    "Mačva District",
    "Moravica District",
    "Nišava District",
    "North Bačka District",
    "North Banat District",
    "Pirot District",
    "Pčinja District",
    "Pomoravlje District",
    "Raška District",
    "Rasina District",
    "South Bačka District",
    "South Banat District",
    "Srem District",
    "Šumadija District",
    "Toplica District",
    "West Bačka District",
    "Zaječar District",
    "Zlatibor District",
]
governorates_seychelles = [
    "Anse aux Pins",
    "Anse Boileau",
    "Anse Etoile",
    "Au Cap",
    "Baie Lazare",
    "Baie Sainte Anne",
    "Beau Vallon",
    "Bel Air",
    "Bel Ombre",
    "Cascade",
    "English River",
    "Glacis",
    "Grand' Anse Mahé",
    "Grand' Anse Praslin",
    "La Digue and Inner Islands",
    "La Rivière Anglaise",
    "Les Mamelles",
    "Mont Buxton",
    "Mont Fleuri",
    "Plaisance",
    "Pointe La Rue",
    "Port Glaud",
    "Roche Caiman",
    "Saint Louis",
    "Takamaka",
]
governorates_sierra_leone = [
    "Eastern Province",
    "Northern Province",
    "North West Province",
    "Southern Province",
    "Western Area",
]
governorates_singapore = [
    # Singapore is a city-state and has no administrative divisions.
    "singapore_city"
]
governorates_slovakia = [
    "Banská Bystrica Region",
    "Bratislava Region",
    "Košice Region",
    "Nitra Region",
    "Prešov Region",
    "Trenčín Region",
    "Trnava Region",
    "Žilina Region",
]
governorates_slovenia = [
    "Carinthia",
    "Central Sava",
    "Central Slovenia",
    "Gorizia",
    "Lower Sava",
    "Primorska-Notranjska",
    "Southeast Slovenia",
    "Slovenian Littoral-Karst",
    "Upper Carniola",
    "Drava",
    "Mura",
    "Savinja",
]
governorates_solomon_islands = [
    "Central Province",
    "Choiseul Province",
    "Guadalcanal Province",
    "Isabel Province",
    "Makira-Ulawa Province",
    "Malaita Province",
    "Rennell and Bellona Province",
    "Temotu Province",
    "Western Province",
    "Honiara (capital territory)",
]
governorates_south_africa = [
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "North West",
    "Northern Cape",
    "Western Cape",
]
governorates_south_korea = [
    "North Chungcheong Province",
    "South Chungcheong Province",
    "Gangwon Province",
    "Gyeonggi Province",
    "North Gyeongsang Province",
    "South Gyeongsang Province",
    "North Jeolla Province",
    "South Jeolla Province",
    "Jeju Special Self-Governing Province",
    "Seoul (special city)",
    "Busan (metropolitan city)",
    "Daegu (metropolitan city)",
    "Daejeon (metropolitan city)",
    "Gwangju (metropolitan city)",
    "Incheon (metropolitan city)",
    "Ulsan (metropolitan city)",
    "Sejong (special self-governing city)",
]
governorates_south_sudan = [
    "Central Equatoria",
    "Eastern Equatoria",
    "Jonglei",
    "Lakes",
    "Northern Bahr el Ghazal",
    "Unity",
    "Upper Nile",
    "Warrap",
    "Western Bahr el Ghazal",
    "Western Equatoria",
]
governorates_spain = [
    "Andalusia",
    "Aragon",
    "Asturias",
    "Balearic Islands",
    "Basque Country",
    "Canary Islands",
    "Cantabria",
    "Castile and León",
    "Castile-La Mancha",
    "Catalonia",
    "Extremadura",
    "Galicia",
    "La Rioja",
    "Madrid Community",
    "Murcia Region",
    "Navarre",
    "Valencian Community",
]
governorates_sri_lanka = [
    "Central Province",
    "Eastern Province",
    "North Central Province",
    "Northern Province",
    "North Western Province",
    "Sabaragamuwa Province",
    "Southern Province",
    "Uva Province",
    "Western Province",
]
governorates_suriname = [
    "Brokopondo District",
    "Commewijne District",
    "Coronie District",
    "Marowijne District",
    "Nickerie District",
    "Para District",
    "Paramaribo District",
    "Saramacca District",
    "Sipaliwini District",
    "Wanica District",
]
governorates_sweden = [
    "Blekinge County",
    "Dalarna County",
    "Gävleborg County",
    "Gotland County",
    "Halland County",
    "Jämtland County",
    "Jönköping County",
    "Kalmar County",
    "Kronoberg County",
    "Norrbotten County",
    "Örebro County",
    "Östergötland County",
    "Skåne County",
    "Stockholm County",
    "Södermanland County",
    "Uppsala County",
    "Värmland County",
    "Västerbotten County",
    "Västernorrland County",
    "Västmanland County",
    "Västra Götaland County",
]
governorates_switzerland = [
    "Aargau",
    "Appenzell Ausserrhoden",
    "Appenzell Innerrhoden",
    "Basel-Landschaft",
    "Basel-Stadt",
    "Bern",
    "Fribourg",
    "Geneva",
    "Glarus",
    "Graubünden",
    "Jura",
    "Lucerne",
    "Neuchâtel",
    "Nidwalden",
    "Obwalden",
    "Schaffhausen",
    "Schwyz",
    "Solothurn",
    "St. Gallen",
    "Thurgau",
    "Ticino",
    "Uri",
    "Valais",
    "Vaud",
    "Zug",
    "Zürich",
]
governorates_taiwan = [
    "Changhua County",
    "Chiayi County",
    "Hsinchu County",
    "Hualien County",
    "Kinmen County",
    "Lienchiang County",
    "Miaoli County",
    "Nantou County",
    "Penghu County",
    "Pingtung County",
    "Taitung County",
    "Yilan County",
    "Yunlin County",
    "Kaohsiung (special municipality)",
    "New Taipei (special municipality)",
    "Taichung (special municipality)",
    "Tainan (special municipality)",
    "Taipei (special municipality)",
    "Taoyuan (special municipality)",
]
governorates_tajikistan = [
    "Sughd Region",
    "Khatlon Region",
    "Gorno-Badakhshan Autonomous Region",
    "Districts of Republican Subordination",
]
governorates_tanzania = [
    "Arusha Region",
    "Dar es Salaam Region",
    "Dodoma Region",
    "Geita Region",
    "Iringa Region",
    "Kagera Region",
    "Katavi Region",
    "Kigoma Region",
    "Kilimanjaro Region",
    "Lindi Region",
    "Manyara Region",
    "Mara Region",
    "Mbeya Region",
    "Morogoro Region",
    "Mtwara Region",
    "Mwanza Region",
    "Njombe Region",
    "Pemba North Region",
    "Pemba South Region",
    "Pwani Region",
    "Rukwa Region",
    "Ruvuma Region",
    "Shinyanga Region",
    "Simiyu Region",
    "Singida Region",
    "Songwe Region",
    "Tabora Region",
    "Tanga Region",
    "Zanzibar Central/South Region",
    "Zanzibar North Region",
    "Zanzibar Urban/West Region",
]
governorates_thailand = [
    "Amnat Charoen",
    "Ang Thong",
    "Bueng Kan",
    "Buriram",
    "Chachoengsao",
    "Chai Nat",
    "Chaiyaphum",
    "Chanthaburi",
    "Chiang Mai",
    "Chiang Rai",
    "Chonburi",
    "Chumphon",
    "Kalasin",
    "Kamphaeng Phet",
    "Kanchanaburi",
    "Khon Kaen",
    "Krabi",
    "Lampang",
    "Lamphun",
    "Loei",
    "Lopburi",
    "Mae Hong Son",
    "Maha Sarakham",
    "Mukdahan",
    "Nakhon Nayok",
    "Nakhon Pathom",
    "Nakhon Phanom",
    "Nakhon Ratchasima",
    "Nakhon Sawan",
    "Nakhon Si Thammarat",
    "Nan",
    "Narathiwat",
    "Nong Bua Lamphu",
    "Nong Khai",
    "Nonthaburi",
    "Pathum Thani",
    "Pattani",
    "Phang Nga",
    "Phatthalung",
    "Phayao",
    "Phetchabun",
    "Phetchaburi",
    "Phichit",
    "Phitsanulok",
    "Phra Nakhon Si Ayutthaya",
    "Phrae",
    "Phuket",
    "Prachinburi",
    "Prachuap Khiri Khan",
    "Ranong",
    "Ratchaburi",
    "Rayong",
    "Roi Et",
    "Sa Kaeo",
    "Sakon Nakhon",
    "Samut Prakan",
    "Samut Sakhon",
    "Samut Songkhram",
    "Saraburi",
    "Satun",
    "Sing Buri",
    "Sisaket",
    "Songkhla",
    "Sukhothai",
    "Suphanburi",
    "Surat Thani",
    "Surin",
    "Tak",
    "Trang",
    "Trat",
    "Ubon Ratchathani",
    "Udon Thani",
    "Uthai Thani",
    "Uttaradit",
    "Yala",
    "Yasothon",
]
governorates_togo = [
    "Savanes Region",
    "Kara Region",
    "Centrale Region",
    "Plateaux Region",
    "Maritime Region",
]
governorates_tonga = [
    "Tongatapu Division",
    "Vavaʻu Division",
    "Haʻapai Division",
    "ʻEua Division",
    "Niuas Division",
]
governorates_trinidad_and_tobago = [
    "Arima Borough Corporation",
    "Chaguanas Borough Corporation",
    "Couva-Tabaquite-Talparo Regional Corporation",
    "Diego Martin Regional Corporation",
    "Eastern Regional Corporation",
    "Mayaro-Rio Claro Regional Corporation",
    "Penal-Debe Regional Corporation",
    "Point Fortin Borough Corporation",
    "Port of Spain City Corporation",
    "Princes Town Regional Corporation",
    "San Fernando City Corporation",
    "Sangre Grande Regional Corporation",
    "Siparia Regional Corporation",
    "Tunapuna-Piarco Regional Corporation",
]
governorates_turkey = [
    "Adana",
    "Adıyaman",
    "Afyonkarahisar",
    "Ağrı",
    "Amasya",
    "Ankara",
    "Antalya",
    "Artvin",
    "Aydın",
    "Balıkesir",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolu",
    "Burdur",
    "Bursa",
    "Çanakkale",
    "Çankırı",
    "Çorum",
    "Denizli",
    "Diyarbakır",
    "Edirne",
    "Elazığ",
    "Erzincan",
    "Erzurum",
    "Eskişehir",
    "Gaziantep",
    "Giresun",
    "Gümüşhane",
    "Hakkâri",
    "Hatay",
    "Isparta",
    "Mersin",
    "Istanbul",
    "İzmir",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kırklareli",
    "Kırşehir",
    "Kocaeli",
    "Konya",
    "Kütahya",
    "Malatya",
    "Manisa",
    "Kahramanmaraş",
    "Mardin",
    "Muğla",
    "Muş",
    "Nevşehir",
    "Niğde",
    "Ordu",
    "Rize",
    "Sakarya",
    "Samsun",
    "Siirt",
    "Sinop",
    "Sivas",
    "Tekirdağ",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Şanlıurfa",
    "Uşak",
    "Van",
    "Yozgat",
    "Zonguldak",
    "Aksaray",
    "Bayburt",
    "Karaman",
    "Kırıkkale",
    "Batman",
    "Şırnak",
    "Bartın",
    "Ardahan",
    "Iğdır",
    "Yalova",
    "Karabük",
    "Kilis",
    "Osmaniye",
    "Düzce",
]
governorates_turkmenistan = [
    "Ahal Province",
    "Balkan Province",
    "Daşoguz Province",
    "Lebap Province",
    "Mary Province",
]
governorates_tuvalu = [
    "Funafuti",
    "Nanumanga",
    "Nanumea",
    "Niutao",
    "Nui",
    "Nukufetau",
    "Nukulaelae",
    "Vaitupu",
]
governorates_uganda = [
    "Central Region",
    "Eastern Region",
    "Northern Region",
    "Western Region",
]
governorates_ukraine = [
    "Cherkasy Oblast",
    "Chernihiv Oblast",
    "Chernivtsi Oblast",
    "Dnipropetrovsk Oblast",
    "Donetsk Oblast",
    "Ivano-Frankivsk Oblast",
    "Kharkiv Oblast",
    "Kherson Oblast",
    "Khmelnytskyi Oblast",
    "Kyiv Oblast",
    "Kirovohrad Oblast",
    "Luhansk Oblast",
    "Lviv Oblast",
    "Mykolaiv Oblast",
    "Odessa Oblast",
    "Poltava Oblast",
    "Rivne Oblast",
    "Sumy Oblast",
    "Ternopil Oblast",
    "Vinnytsia Oblast",
    "Volyn Oblast",
    "Zakarpattia Oblast",
    "Zaporizhzhia Oblast",
    "Zhytomyr Oblast",
    "Crimea (autonomous republic)",
    "Kyiv (city)",
    "Sevastopol (city)",
]
governorates_united_kingdom = [
    "England",
    "Scotland",
    "Wales",
    "Northern Ireland",
]
governorates_united_states = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
    "District of Columbia",
]
governorates_uruguay = [
    "Artigas Department",
    "Canelones Department",
    "Cerro Largo Department",
    "Colonia Department",
    "Durazno Department",
    "Flores Department",
    "Florida Department",
    "Lavalleja Department",
    "Maldonado Department",
    "Montevideo Department",
    "Paysandú Department",
    "Río Negro Department",
    "Rivera Department",
    "Rocha Department",
    "Salto Department",
    "San José Department",
    "Soriano Department",
    "Tacuarembó Department",
    "Treinta y Tres Department",
]
governorates_uzbekistan = [
    "Andijan Region",
    "Bukhara Region",
    "Fergana Region",
    "Jizzakh Region",
    "Namangan Region",
    "Navoiy Region",
    "Qashqadaryo Region",
    "Samarqand Region",
    "Sirdaryo Region",
    "Surxondaryo Region",
    "Tashkent Region",
    "Tashkent City",
    "Karakalpakstan Republic",
]
governorates_vanuatu = [
    "Malampa Province",
    "Penama Province",
    "Sanma Province",
    "Shefa Province",
    "Tafea Province",
    "Torba Province",
]
governorates_venezuela = [
    "Amazonas State",
    "Anzoátegui State",
    "Apure State",
    "Aragua State",
    "Barinas State",
    "Bolívar State",
    "Carabobo State",
    "Cojedes State",
    "Delta Amacuro State",
    "Falcón State",
    "Guárico State",
    "Lara State",
    "Mérida State",
    "Miranda State",
    "Monagas State",
    "Nueva Esparta State",
    "Portuguesa State",
    "Sucre State",
    "Táchira State",
    "Trujillo State",
    "Vargas State",
    "Yaracuy State",
    "Zulia State",
    "Capital District",
    "Federal Dependencies",
]
governorates_vietnam = [
    "An Giang",
    "Bà Rịa-Vũng Tàu",
    "Bạc Liêu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bắc Ninh",
    "Bến Tre",
    "Bình Định",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Cà Mau",
    "Cao Bằng",
    "Đắk Lắk",
    "Đắk Nông",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Tĩnh",
    "Hải Dương",
    "Hậu Giang",
    "Hòa Bình",
    "Hưng Yên",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Lâm Đồng",
    "Lạng Sơn",
    "Lào Cai",
    "Long An",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Phú Yên",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên-Huế",
    "Tiền Giang",
    "Trà Vinh",
    "Tuyên Quang",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái",
    "Cần Thơ",
    "Đà Nẵng",
    "Hải Phòng",
    "Hà Nội",
    "Hồ Chí Minh City",
]
governorates_zambia = [
    "Central Province",
    "Copperbelt Province",
    "Eastern Province",
    "Luapula Province",
    "Lusaka Province",
    "Muchinga Province",
    "Northern Province",
    "North-Western Province",
    "Southern Province",
    "Western Province",
]
governorates_zimbabwe = [
    "Bulawayo Province",
    "Harare Province",
    "Manicaland Province",
    "Mashonaland Central Province",
    "Mashonaland East Province",
    "Mashonaland West Province",
    "Masvingo Province",
    "Matabeleland North Province",
    "Matabeleland South Province",
    "Midlands Province",
]
governorates_peru = [
    "Amazonas",
    "Áncash",
    "Apurímac",
    "Arequipa",
    "Ayacucho",
    "Cajamarca",
    "Callao",
    "Cusco",
    "Huancavelica",
    "Huánuco",
    "Ica",
    "Junín",
    "La Libertad",
    "Lambayeque",
    "Lima",
    "Loreto",
    "Madre de Dios",
    "Moquegua",
    "Pasco",
    "Piura",
    "Puno",
    "San Martín",
    "Tacna",
    "Tumbes",
    "Ucayali",
]
governorates_saint_kitts_and_nevis = [
    "Saint George Basseterre Parish",
    "Saint Peter Basseterre Parish",
    "Saint Mary Cayon Parish",
    "Saint John Capisterre Parish",
    "Saint Paul Capisterre Parish",
    "Saint Anne Sandy Point Parish",
    "Saint Paul Charlestown Parish",
    "Saint Thomas Lowland Parish",
    "Saint James Windward Parish",
    "Christ Church Nichola Town Parish",
    "Saint Thomas Middle Island Parish",
    "Trinity Palmetto Point Parish",
    "Saint George Gingerland Parish",
    "Saint John Figtree Parish",
]
governorates_vatican_city = [
    # The Vatican City is a city-state and has no administrative divisions.
    "vatican City"
]
governorates_yemen = [
    "Abyan",
    "Aden",
    "Al Bayda",
    "Al Dhale'e",
    "Al Hudaydah",
    "Al Jawf",
    "Al Mahrah",
    "Hadhramaut",
    "Hajjah",
    "Ibb",
    "Lahij",
    "Ma'rib",
    "Raymah",
    "Saada",
    "Sana'a",
    "Sana'a City",
    "Shabwah",
    "Socotra",
    "Taiz",
]
governorates_colombia = [
    "Amazonas Department",
    "Antioquia Department",
    "Arauca Department",
    "Atlántico Department",
    "Bolívar Department",
    "Boyacá Department",
    "Caldas Department",
    "Caquetá Department",
    "Casanare Department",
    "Cauca Department",
    "Cesar Department",
    "Chocó Department",
    "Córdoba Department",
    "Cundinamarca Department",
    "Guainía Department",
    "Guaviare Department",
    "Huila Department",
    "La Guajira Department",
    "Magdalena Department",
    "Meta Department",
    "Nariño Department",
    "Norte de Santander Department",
    "Putumayo Department",
    "Quindío Department",
    "Risaralda Department",
    "San Andrés and Providencia Department",
    "Santander Department",
    "Sucre Department",
    "Tolima Department",
    "Valle del Cauca Department",
    "Vaupés Department",
    "Vichada Department",
    "Bogotá (capital district)",
]
governorates_croatia = [
    "Bjelovar-Bilogora County",
    "Brod-Posavina County",
    "Dubrovnik-Neretva County",
    "Istria County",
    "Karlovac County",
    "Koprivnica-Križevci County",
    "Krapina-Zagorje County",
    "Lika-Senj County",
    "Međimurje County",
    "Osijek-Baranja County",
    "Požega-Slavonia County",
    "Primorje-Gorski Kotar County",
    "Šibenik-Knin County",
    "Sisak-Moslavina County",
    "Split-Dalmatia County",
    "Varaždin County",
    "Virovitica-Podravina County",
    "Vukovar-Srijem County",
    "Zadar County",
    "Zagreb County",
    "Zagreb City",
]
governorates_georgia = [
    "Abkhazia (autonomous republic)",
    "Adjara (autonomous republic)",
    "Guria",
    "Imereti",
    "Kakheti",
    "Kvemo Kartli",
    "Mtskheta-Mtianeti",
    "Racha-Lechkhumi and Kvemo Svaneti",
    "Samegrelo-Zemo Svaneti",
    "Samtskhe-Javakheti",
    "Shida Kartli",
    "Tbilisi (capital city)",
]
payment_methods = [
    "Cash",
    "Cash on Delivery",
    "Bank Transfer",
    "Checks",
    "Fawry",
    "Vodafone Cash",
    "Etisalat Cash",
    "Orange Money",
    "We Pay",
    "CIB Smart Wallet",
    "QNB Al Ahli E-Wallet",
    "BM Wallet",
    "Easycash",
    "EBank Wallet (Gebe)",
    "e& money",
    "Paymob",
    "FawryPay",
    "OPay",
    "Paytabs",
    "PayPal",
    "Instalment Plans",
    "Point of Sale (POS)",
]
roles = [
    "Administrator",
    "Manager",
    "Supervisor",
    "Instructor",
    "Assistant Instructor",
    "Student",
    "Tutor",
    "HR Manager",
    "Financial Officer",
    "Marketing Specialist",
    "IT Support",
    "Cleaner",
    "Security Guard",
    "Librarian",
    "Receptionist",
    "Maintenance Staff",
    "Data Entry",
]


governorates = [
    governorates_egypt,
    governorates_saudi_arabia,
    governorates_palestine,
    governorates_jordan,
    governorates_united_arab_emirates,
    governorates_tunisia,
    governorates_algeria,
    governorates_djibouti,
    governorates_sudan,
    governorates_syria,
    governorates_somalia,
    governorates_iraq,
    governorates_oman,
    governorates_qatar,
    governorates_kuwait,
    governorates_lebanon,
    governorates_libya,
    governorates_morocco,
    governorates_mauritania,
    governorates_bahrain,
    governorates_comoros,
    governorates_afghanistan,
    governorates_albania,
    governorates_andorra,
    governorates_angola,
    governorates_antigua_and_barbuda,
    governorates_argentina,
    governorates_armenia,
    governorates_australia,
    governorates_austria,
    governorates_azerbaijan,
    governorates_bahamas,
    governorates_bangladesh,
    governorates_barbados,
    governorates_belarus,
    governorates_belgium,
    governorates_belize,
    governorates_benin,
    governorates_bhutan,
    governorates_bolivia,
    governorates_bosnia_and_herzegovina,
    governorates_botswana,
    governorates_brazil,
    governorates_brunei,
    governorates_bulgaria,
    governorates_burkina_faso,
    governorates_burundi,
    governorates_cabo_verde,
    governorates_cambodia,
    governorates_cameroon,
    governorates_canada,
    governorates_central_african_republic,
    governorates_chad,
    governorates_chile,
    governorates_china,
    governorates_republic_of_the_congo,
    governorates_democratic_republic_of_the_congo,
    governorates_costa_rica,
    governorates_cote_d_ivoire,
    governorates_cuba,
    governorates_cyprus,
    governorates_czech_republic,
    governorates_denmark,
    governorates_dominica,
    governorates_dominican_republic,
    governorates_east_timor,
    governorates_ecuador,
    governorates_el_salvador,
    governorates_equatorial_guinea,
    governorates_eritrea,
    governorates_estonia,
    governorates_eswatini,
    governorates_ethiopia,
    governorates_fiji,
    governorates_finland,
    governorates_france,
    governorates_gabon,
    governorates_gambia,
    governorates_germany,
    governorates_ghana,
    governorates_greece,
    governorates_grenada,
    governorates_guatemala,
    governorates_guinea,
    governorates_guinea_bissau,
    governorates_guyana,
    governorates_haiti,
    governorates_honduras,
    governorates_hungary,
    governorates_iceland,
    governorates_india,
    governorates_indonesia,
    governorates_iran,
    governorates_ireland,
    governorates_italy,
    governorates_jamaica,
    governorates_japan,
    governorates_kazakhstan,
    governorates_kenya,
    governorates_kiribati,
    governorates_kosovo,
    governorates_kyrgyzstan,
    governorates_laos,
    governorates_latvia,
    governorates_lesotho,
    governorates_liberia,
    governorates_liechtenstein,
    governorates_lithuania,
    governorates_luxembourg,
    governorates_madagascar,
    governorates_malawi,
    governorates_malaysia,
    governorates_maldives,
    governorates_mali,
    governorates_malta,
    governorates_marshall_islands,
    governorates_mauritius,
    governorates_mexico,
    governorates_micronesia,
    governorates_moldova,
    governorates_monaco,
    governorates_mongolia,
    governorates_mozambique,
    governorates_myanmar,
    governorates_namibia,
    governorates_nauru,
    governorates_netherlands,
    governorates_nicaragua,
    governorates_niger,
    governorates_nigeria,
    governorates_north_korea,
    governorates_north_macedonia,
    governorates_norway,
    governorates_pakistan,
    governorates_palau,
    governorates_panama,
    governorates_papua_new_guinea,
    governorates_paraguay,
    governorates_poland,
    governorates_portugal,
    governorates_romania,
    governorates_russia,
    governorates_rwanda,
    governorates_saint_lucia,
    governorates_saint_vincent_and_the_grenadines,
    governorates_samoa,
    governorates_san_marino,
    governorates_sao_tome_and_principe,
    governorates_senegal,
    governorates_serbia,
    governorates_seychelles,
    governorates_sierra_leone,
    governorates_singapore,
    governorates_slovakia,
    governorates_slovenia,
    governorates_solomon_islands,
    governorates_south_africa,
    governorates_south_korea,
    governorates_south_sudan,
    governorates_spain,
    governorates_sri_lanka,
    governorates_suriname,
    governorates_sweden,
    governorates_switzerland,
    governorates_taiwan,
    governorates_tajikistan,
    governorates_tanzania,
    governorates_thailand,
    governorates_togo,
    governorates_tonga,
    governorates_trinidad_and_tobago,
    governorates_turkey,
    governorates_turkmenistan,
    governorates_tuvalu,
    governorates_uganda,
    governorates_ukraine,
    governorates_united_kingdom,
    governorates_united_states,
    governorates_uruguay,
    governorates_uzbekistan,
    governorates_vanuatu,
    governorates_venezuela,
    governorates_vietnam,
    governorates_zambia,
    governorates_zimbabwe,
    governorates_peru,
    governorates_saint_kitts_and_nevis,
    governorates_vatican_city,
    governorates_yemen,
    governorates_colombia,
    governorates_croatia,
    governorates_georgia,
]